class DiamondRunner
{
    public static void main(String[] args)
	{
		String 
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();
		String
		System.out.println();

	}
}