class JacketRunner{
public static void main(String[] args)
{       
        String cellphone="daily uses";
		System.out.println(cellphone);
		String wifi="many people can access";
		System.out.println(wifi);
		String bucket="for Bath";j
		System.out.println(bucket);
		String sweet="for eating";
		System.out.println(sweet);
		String shampo="for hair used";
		System.out.println(shampo);
		String lipstick="for lips";
		System.out.println(lipstick);
		String wine="for chill";
		System.out.println(wine);
		String butterfly="beautiful";
		System.out.println(butterfly);
		String sheva=" masala tasty";
		System.out.println(sheva);
		String shoes="for running";
		System.out.println(shoes);
		String world="for travelling";
		System.out.println(world);
		String pillow="sleeping purpose";
		System.out.println(pillow);
		String eyeshadow="used for eye makeup";
		System.out.println(eyeshadow);
		String bangles="hand look gorgeous";
		System.out.println(bangles);
		String curtain="window closing";
		System.out.println(curtain);
		String fan="for air";
		System.out.println(fan);
		String cream="very tasty";
		System.out.println(cream);
		String eartops="for ear we can use";
		System.out.println(eartops);
		String blanket="to keep sleeping person warm";
		System.out.println(blanket);
		String cold="winter season";
		System.out.println(cold);
		String summer="sun is hot";
		System.out.println(summer);
		String water="for health good";
		System.out.println(water);
		String black="fav colour";
		System.out.println(black);
		String bike="riding";
		System.out.println(bike);
		String tab="for working";
		System.out.println(tab);
		String whatsapp="chatting";
		System.out.println( whatsapp);
		String insta="scrolling";
		System.out.println(insta);
		String tiger="cruel";
		System.out.println(tiger);
		String cow=" god";
		System.out.println(cow);
		String jamoon="very tasty";
		System.out.println(jamoon);

		String girl="Trust your journey.";
		System.out.println(girl);
		String boy="Create happiness.";
		System.out.println(boy);
		String bottle="Listen more.";
		System.out.println(bottle);
		String pant="Speak kindly.";
		System.out.println(pant);
		String clip="Celebrate life.";
		System.out.println(clip);
		String teddy="Enjoy the moment.";
		System.out.println(teddy);
		String top="Keep moving forward.";
		System.out.println(top);
		String mirror="Never give up.";
		System.out.println(mirror);
		String animal="Breathe deeply.";
		System.out.println(animal);
		String towel="Live authentically.";
		System.out.println(towel);
		String handel="Be courageous.";
		System.out.println(handel);
		String box="Grow through challenges.";
		System.out.println(box);
		String chain="Be the light.";
		System.out.println(chain);
		String wire="Stay humble.";
		System.out.println(wire);
		String krutha="Follow your heart.";
		System.out.println(krutha);
		String tv="Dance in the rain.";
		System.out.println(tv);
		String ac="Find beauty everywhere.";
		System.out.println(ac);
		String earphone="Radiate positivity.";
		System.out.println(earphone);
		String window="Spread kindness.";
		System.out.println(window);
		String bulb="Value relationships.";
		System.out.println(bulb);	
		String watch="Be present.";
		System.out.println(watch);
		String band="Laugh often.";
		System.out.println(band);
		String finger="Stay curious.";
		System.out.println(finger);
		String hair="Savor simplicity.";
		System.out.println(hair);
		String bed="Practice gratitude.";
		System.out.println(bed);
		String plate="Discover inner peace.";
		System.out.println(plate);
		String city="Inspire others.";
		System.out.println(city);		
		String ring="Count your blessings.";
		System.out.println(ring);
		String soap="Choose happiness.";
		System.out.println(soap);	
		String comb="Stay focused.";
		System.out.println(comb);
		String greating="goodmorning.";
		System.out.println(greating);
        String str="hello word";
		System.out.println(str);
		String test="Now is the time for all good ";
		System.out.println(test);
		String ball="men to come to the aid of their country";
		System.out.println(ball);
		String doll="Time heals ";
		System.out.println(doll);
		String brush="Love conquers.";
		System.out.println(brush);
		String jug="Dream big.";
		System.out.println(jug);
		String laptop="Stay strong.";
		System.out.println(laptop);
		String bag="Be kind.";
		System.out.println(bag);
		String dog="Chase joy";
		System.out.println(dog);
		String pen="Learn daily";
		System.out.println(pen);
		String mobile="Forgive often.";
		System.out.println(mobile);
		String sky="Believe in yourself.";
		System.out.println(sky);
		String kite="Find your passion.";
		System.out.println(kite);	
		String blue="Seek adventure.";
		System.out.println(blue);		
}}