CREATE TABLE employee_details(employee_name varchar(20), employee_id bigint, phone_no bigint);
ALTER TABLE employee_details ADD COLUMN (address varchar(20),sl_no int,department varchar(10), city_name varchar(15),pincode int);
ALTER TABLE employee_details DROP COLUMN city_name;
ALTER TABLE employee_details DROP COLUMN pincode ;
ALTER TABLE employee_details RENAME COLUMN address TO place;
ALTER TABLE employee_details RENAME COLUMN phone_no TO mobile_no;
ALTER TABLE employee_details RENAME COLUMN employee_name TO worker_name;
ALTER TABLE employee_details RENAME COLUMN department TO sector;
ALTER TABLE employee_details MODIFY COLUMN sl_no bigint;
ALTER TABLE employee_details ADD COLUMN pincode int;
ALTER TABLE employee_details MODIFY COLUMN pincode bigint;
ALTER TABLE employee_details MODIFY COLUMN employee_id int;
ALTER TABLE employee_details MODIFY COLUMN mobile_no int;
ALTER TABLE employee_details ADD COLUMN experience int;
ALTER TABLE employee_details MODIFY COLUMN experience bigint;
CREATE TABLE airport_details(airport_name varchar(20),airport_address varchar(20),airport_id bigint);
ALTER TABLE airport_details ADD COLUMN(contact_no bigint,city_name varchar(10), city_pincode int,visa_no int, no_of_passenger int);
ALTER TABLE airport_details DROP COLUMN city_name;
ALTER TABLE airport_details DROP COLUMN airport_name;
ALTER TABLE airport_details RENAME COLUMN airport_id TO airport_no;
ALTER TABLE airport_details RENAME COLUMN airport_address TO airport_place;
ALTER TABLE airport_details RENAME COLUMN city_pincode TO pincode;
ALTER TABLE airport_details RENAME COLUMN visa_no TO visa_id;
ALTER TABLE airport_details RENAME COLUMN no_of_passenger TO passenger_no;
ALTER TABLE airport_details MODIFY COLUMN pincode bigint;
ALTER TABLE airport_details MODIFY COLUMN visa_id bigint;
ALTER TABLE airport_details MODIFY COLUMN contact_no int;
ALTER TABLE airport_details CHANGE COLUMN contact_no int;
