
CREATE DATABASE nidhi;
USE nidhi;
CREATE TABLE NIDHI_INFO(ID INT,NAME VARCHAR(20), PHONE_NO BIGINT);
CREATE TABLE REVI_INFO(ID INT,NAME VARCHAR(20), PHONE_NO BIGINT);
INSERT INTO INFO_VALUES(20,"PRATIK",456,8867554758);
SELECT * FROM INFO